name: Release dockware/essentials:*

#only manually
on:
  workflow_dispatch:

jobs:
  
    build-essentials-latest:
      name: Release essentials:latest
      runs-on: ubuntu-latest
      steps:
        - name: Clone Code
          uses: actions/checkout@v2
    
        - name: Install Dependencies
          run: make install
    
        - name: ORCA Generate
          run: make generate -B
    
        - name: Build Image
          run: make build image=essentials tag=latest -B
    
        - name: Run SVRUnit Tests
          run: make test image=essentials tag=latest -B
          
        - name: Store SVRUnit Report
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: svrunit_report
            retention-days: 3
            path: |
                .reports


        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
        - name: Push to Docker Hub
          run: docker push dockware/essentials:latest